# Generated by Django 3.2.6 on 2022-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
