# Generated by Django 3.2.6 on 2022-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapi',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
